#pragma once

#include <atomic>
#include <future>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

// Forward declarations of the Wayland types we hold pointers to, so this
// header stays usable without including wayland-client.h.
struct wl_display;
struct wl_registry;
struct wl_compositor;
struct wl_shm;
struct wl_surface;
struct wl_buffer;
struct wl_output;
struct zwlr_layer_shell_v1;
struct zwlr_layer_surface_v1;

// Linux debug overlay (Wayland). Mirrors the DiscordOverlay API used on
// Windows so object_detection_image_mt.cpp can drive either backend through
// a single `DebugOverlay` alias.
//
// Implementation: a fullscreen, click-through wlr-layer-shell surface on the
// overlay layer (works on KWin and wlroots compositors), backed by wl_shm
// ARGB8888 buffers painted directly in software — no cairo/EGL. Detection
// boxes are 2px opaque outlines with a per-label color, a "name 0.87" label
// drawn in a tiny built-in 5x7 bitmap font, plus a stats line (top-left).
// Wayland protocol bindings are vendored under src/wayland/ (generated by
// wayland-scanner from wlr-protocols / wayland-protocols; see src/wayland/README.md).
//
// Threading (same pattern as CS2Miam's OverlayWayland): a dedicated thread
// owns the entire Wayland connection and event dispatch. setDetections() /
// setStats() are called from the detection thread; they swap state under a
// short mutex, bump a generation counter, and poke an eventfd that wakes the
// render thread.
class LinuxOverlay {
public:
    // Detection box in screen pixel coordinates (same space as the captured
    // frame, which spans the whole output).
    struct DetectionBox {
        float x, y, w, h;
        int label;
        float confidence;
    };

    LinuxOverlay() = default;
    // screenW/screenH: physical size of the captured output — used to pick the
    // same monitor the capture runs on (falls back to the largest output).
    explicit LinuxOverlay(int screenW, int screenH) : _preferredW(screenW), _preferredH(screenH) {}
    ~LinuxOverlay();

    LinuxOverlay(const LinuxOverlay &) = delete;
    LinuxOverlay &operator=(const LinuxOverlay &) = delete;

    bool start();
    void stop();
    bool isRunning() const { return _running.load(std::memory_order_relaxed); }

    void setLabelNames(const std::vector<std::string> &names);
    void setDetections(std::vector<DetectionBox> boxes);
    void setStats(double detectMs, int fps);

    // Pixel space the incoming boxes are expressed in (the captured output's
    // size). The layer surface can be configured at a different size, so paint()
    // maps boxes by surface/source. 0 (default) falls back to the size passed to
    // the constructor.
    void setSourceSize(int w, int h);

private:
    struct Buffer {
        wl_buffer *buffer = nullptr;
        uint32_t *data = nullptr;
        size_t size = 0;
        bool busy = false;
        // Scene bounding box last painted into THIS buffer (int pixels,
        // half-open). Fresh memfd pages are zero = fully transparent.
        int x0 = 0, y0 = 0, x1 = 0, y1 = 0;
        bool hasPaint = false;
    };

    struct OutputInfo {
        wl_output *output = nullptr;
        std::string name;    // connector name, e.g. "DP-1" (wl_output v4+)
        int width = 0;       // current mode, physical pixels
        int height = 0;
    };

    // ---- Shared with the detection thread ----
    std::thread _thread;
    std::mutex _stateMutex;
    std::vector<DetectionBox> _sharedBoxes; // guarded by _stateMutex
    std::vector<std::string> _sharedLabels; // guarded by _stateMutex
    double _sharedDetectMs = 0.0;           // guarded by _stateMutex
    int _sharedFps = 0;                     // guarded by _stateMutex
    std::atomic<uint64_t> _sharedGen{0};
    std::atomic<bool> _threadRun{false};
    std::atomic<bool> _running{false};
    int _wakeFd = -1; // eventfd; detection thread pokes it on publish
    std::promise<bool> _initResult;

    // ---- Render-thread-private ----
    wl_display *_display = nullptr;
    wl_registry *_registry = nullptr;
    wl_compositor *_compositor = nullptr;
    wl_shm *_shm = nullptr;
    zwlr_layer_shell_v1 *_layerShell = nullptr;
    wl_surface *_surface = nullptr;
    zwlr_layer_surface_v1 *_layerSurface = nullptr;
    std::vector<OutputInfo *> _outputs;
    int _preferredW = 0; // captured output size, for pickOutput()
    int _preferredH = 0;

    std::atomic<int> _sourceW{0}; // setSourceSize(); 0 = use _preferred* above
    std::atomic<int> _sourceH{0};

    Buffer _buffers[2];
    Buffer *_lastAttached = nullptr; // buffer content currently on screen
    // Screen-space rect of the last COMMITTED scene (either buffer), for
    // damage tracking — independent of per-buffer paint rects.
    int _commitX0 = 0, _commitY0 = 0, _commitX1 = 0, _commitY1 = 0;
    bool _commitValid = false;
    int _width = 0;
    int _height = 0;
    bool _configured = false;

    std::vector<DetectionBox> _boxes;  // render thread's snapshot
    std::vector<std::string> _labels;
    double _detectMs = 0.0;
    int _fps = 0;
    uint64_t _paintedGen = 0;
    bool _scenePending = false;

    // Wayland callbacks (all run on the render thread).
    static void registryGlobal(void *data, wl_registry *reg, uint32_t name,
                               const char *iface, uint32_t version);
    static void registryGlobalRemove(void *, wl_registry *, uint32_t) {}
    static void layerConfigure(void *data, zwlr_layer_surface_v1 *ls,
                               uint32_t serial, uint32_t w, uint32_t h);
    static void layerClosed(void *data, zwlr_layer_surface_v1 *);
    static void bufferRelease(void *data, wl_buffer *);
    static void outputGeometry(void *, wl_output *, int32_t, int32_t, int32_t,
                               int32_t, int32_t, const char *, const char *, int32_t) {}
    static void outputMode(void *data, wl_output *, uint32_t flags, int32_t w, int32_t h, int32_t);
    static void outputDone(void *, wl_output *) {}
    static void outputScale(void *, wl_output *, int32_t) {}
    static void outputName(void *data, wl_output *, const char *name);
    static void outputDescription(void *, wl_output *, const char *) {}

    wl_output *pickOutput() const;
    bool initWayland();
    void teardown();
    void threadMain();

    bool initBuffer(Buffer &b, int w, int h);
    void destroyBuffer(Buffer &b);
    void allocBuffers(int w, int h);

    void maybePaint();
    void paint(Buffer &buf);
};
